---
title: "Barking Up the Right Tree: Analyzing Trends, Geographic Hotspots, and Contributing Factors of NYC Dogbites"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```

*Shiyu Zhang, sz3319, Weiqi Liang, wl3011, Zhenkun Fang, zf2352, Zeqi Li, zl3545*

<br><br> 

## Motivation

Dogs are often cherished as "man's best friend", but the rising number of dog bite incidents poses a growing public health concern. In 2022, dog bites were among the top 15 causes of nonfatal emergency department visits across all age groups. This project explores the factors contributing to dog bite incidents, including dog-specific traits like breed, age, gender, and spay/neuter status, as well as their geographical patterns and trends over time. By analyzing bite rates across different zip code areas, we aim to identify hotspots and better understand the relationship between dog characteristics and bite frequency. The findings will support efforts to develop data-driven strategies for preventing dog bites and improving public safety.

<br><br> 

## Related Work

We were inspired to perform this analysis after discovering dog bites data from the [NYC DOHMH](https://www.health.ny.gov/health_care/medicaid/redesign/ehr/registry/nycdohmh.htm). The New York State Department of Health (the Department) has been overseeing the health, safety, and well-being of New Yorkers since 1901 – from vaccinations to utilizing new developments in science as critical tools in the prevention and treatment of infectious diseases. The data could be found on [NYC OpenData](https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg/about_data). Given that the dataset includes details such as the date of each dog bite, the borough, and various dog demographic variables, we saw this as an excellent opportunity to apply and explore the visualization and interactivity concepts covered in class.

<br><br> 

## Initial Questions

We began by exploring trends in NYC dog bite incidents over time, along with their associations with dog demographics and spay/neuter status. We were interested in the following:

1. Which dog breeds are most frequently associated with dog bite incidents?

2. Has the incidence rate of dog bites shown a decline over the years?

3. Is the incidence rate of dog bites influenced by the dog's gender and neuter status?

<br><br> 

## Evolution of Questions

As our project evolved, we delved into more in-depth questions:

1. Is the incidence rate of dog bites associated with the number of registered dog licenses?

2. Can we utilize a regression model to investigate the spatial correlations between dog bite incidents and dog licenses?

3. Which model is most suitable for analyzing the cumulative impact of various factors on dog bite incidents?

<br><br> 

## Data

The dataset utilized for analyzing and visualizing dog bite cases in New York City includes information on various factors such as sex, breed, and age. The data, covering the period from 2015 to 2022, were sourced from [NYC OpenData](https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg/about_data). Data is collected from reports received online, mail, fax or by phone to 311 or NYC DOHMH Animal Bite Unit. Each record represents a single dog bite incident.

Another dataset used in this project documents active dog licenses in New York City for a given year. This data is derived from the DOHMH Dog Licensing System, which facilitates the application and renewal of dog licenses. The dataset is also sourced from [NYC OpenData](https://data.cityofnewyork.us/Health/NYC-Dog-Licensing-Dataset/nu7n-tubp/about_data). 

The dog bite dataset we utilized includes the following variables:

* `UniqueID`: Unique dog bite case identifier.
* `DateOfBite`: Date bitten.
* `Species`: Animal Type (Dog).
* `Breed`: Breed type.
* `Age`: Dog's age at time of bite. Numbers with 'M' indicate months.
* `Gender`: Sex of Dog. M=Male, F=Female, U=Unknown.
* `SpayNeuter`: Surgical removal of dog's reproductive organs. True (reported to DOHMH as Spayed or Neutered), False (Unknown or Not Spayed or Neutered).
* `Borough`: Dog bite Borough. Other' indicates that the bite took place outside New York City.
* `ZipCode`: Dog bite Zipcode. Blank ZipCode indicates that information was not available.

The NYC dog licensing dataset we utilized includes the following variables:

* `AnimalName`: User-provided dog name (unless specified otherwise).
* `AnimalGender`: M (Male) or F (Female) dog gender.
* `AnimalBirthYear`: Year dog was born.
* `BreedName`: Dog breed.
* `ZipCode`: Owner zip code.
* `LicenseIssuedDate`: Date the dog license was issued.
* `LicenseExpiredDate`: Date the dog license expires.
* `Extract Year`: Year the data was extracted.

<br><br> 

## Exploratory Analysis

## Additional analysis

## Discussion

## References